DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('tualocms_section','CMS - Abschnitte','',0,'title','title','title',1,'','','','',1,'cellmodel','',0,'','','','Content-Management-System','',1,'','','','XlsxWriter','tualocms_section {DATE} {TIME}',0,1000,0,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic') ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
REPLACE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('tualocms_section','content',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'longtext','','longtext',4294967295,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('tualocms_section','pug_file',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'varchar','MUL','varchar(50)',50,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('tualocms_section','title',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'YES',NULL,1,NULL,'longtext','','longtext',4294967295,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('tualocms_section','tualocms_section','{:uuid()}',0,0,'',1,0,'','','NO','',1,'','varchar','PRI','varchar(36)',36,NULL,NULL,'utf8mb4','select,insert,update,references',1,0,'',''),
('tualocms_section','valid_from','2023-01-01 00:00:00',0,0,'',0,0,'','','NO','',1,'','datetime','','datetime',NULL,NULL,NULL,NULL,'select,insert,update,references',1,0,'',''),
('tualocms_section','valid_until','2023-12-31 23:59:59',0,0,'',0,0,'','','NO','',1,'','datetime','','datetime',NULL,NULL,NULL,NULL,'select,insert,update,references',1,0,'','');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('tualocms_section','content','DE','Inhalt','gridcolumn',NULL,2,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('tualocms_section','pug_file','DE','Template','column_ds_pug_templates_id',NULL,3,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('tualocms_section','title','DE','Titel','gridcolumn',NULL,1,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('tualocms_section','tualocms_section','DE','ID','gridcolumn',NULL,0,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('tualocms_section','valid_from','DE','von','gridcolumn',NULL,4,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('tualocms_section','valid_until','DE','bis','gridcolumn',NULL,5,'','','',0,1,'',0,1.00,'ASC','left','',NULL);
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('tualocms_section','content','DE','Inhalt','cherrymarkdown','Allgemein/Angaben',2,0,1,0,'1',1.00,'\'\''),
('tualocms_section','pug_file','DE','Template','combobox_ds_pug_templates_id','Allgemein/Angaben',3,0,1,0,'1',1.00,'\'\''),
('tualocms_section','title','DE','Titel','textfield','Allgemein/Angaben',1,0,1,0,'1',1.00,'\'\''),
('tualocms_section','tualocms_section','DE','ID','displayfield','Allgemein/Angaben',0,0,1,0,'1',1.00,'\'\''),
('tualocms_section','valid_from','DE','von','datetimefield','Allgemein/Angaben',4,0,1,0,'1',1.00,'\'\''),
('tualocms_section','valid_until','DE','bis','datetimefield','Allgemein/Angaben',5,0,1,0,'1',1.00,'\'\'');
INSERT  IGNORE INTO `ds_dropdownfields` (`table_name`, `name`, `idfield`, `displayfield`, `filterconfig`) VALUES ('tualocms_section','tualocms_section','tualocms_section','title','');
INSERT  IGNORE INTO `ds_reference_tables` (`table_name`, `reference_table_name`, `columnsdef`, `constraint_name`, `active`, `searchable`, `autosync`, `position`, `path`, `existsreal`, `tabtitle`) VALUES ('tualocms_section','ds_pug_templates','{\"pug_file\":\"id\"}','fk_tualocms_section_pug_file',1,0,0,999,'',1,'');
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','tualocms_section',1,1,1,1,0);
