DELIMITER ;
INSERT INTO `ds` (`table_name`, `title`, `reorderfield`, `use_history`, `searchfield`, `displayfield`, `sortfield`, `searchany`, `hint`, `overview_tpl`, `sync_table`, `writetable`, `globalsearch`, `listselectionmodel`, `sync_view`, `syncable`, `cssstyle`, `alternativeformxtype`, `read_table`, `class_name`, `special_add_panel`, `existsreal`, `character_set_name`, `read_filter`, `listxtypeprefix`, `phpexporter`, `phpexporterfilename`, `combined`, `default_pagesize`, `allowForm`, `listviewbaseclass`, `showactionbtn`, `modelbaseclass`) VALUES ('tualocms_page_middleware','CMS - Seitenmiddleware','position',0,'tualocms_middleware','tualocms_middleware','position',0,'','','','',0,'cellmodel','',0,'','','','Content-Management-System','',1,'','','','XlsxWriter','tualocms_page_middleware {DATE} {TIME}',0,1000,0,'Tualo.DataSets.ListView',1,'Tualo.DataSets.model.Basic') ON DUPLICATE KEY UPDATE title=VALUES(title), reorderfield=VALUES(reorderfield), use_history=VALUES(use_history), searchfield=VALUES(searchfield), displayfield=VALUES(displayfield), sortfield=VALUES(sortfield), searchany=VALUES(searchany), hint=VALUES(hint), overview_tpl=VALUES(overview_tpl), sync_table=VALUES(sync_table), writetable=VALUES(writetable), globalsearch=VALUES(globalsearch), listselectionmodel=VALUES(listselectionmodel), sync_view=VALUES(sync_view), syncable=VALUES(syncable), cssstyle=VALUES(cssstyle), alternativeformxtype=VALUES(alternativeformxtype), read_table=   VALUES(read_table), class_name=VALUES(class_name), special_add_panel=VALUES(special_add_panel), existsreal=VALUES(existsreal), character_set_name=VALUES(character_set_name), read_filter=VALUES(read_filter), listxtypeprefix=VALUES(listxtypeprefix), phpexporter=VALUES(phpexporter), phpexporterfilename=VALUES(phpexporterfilename), combined=VALUES(combined), default_pagesize=VALUES(default_pagesize), allowForm=VALUES(allowForm), listviewbaseclass=VALUES(listviewbaseclass), showactionbtn=VALUES(showactionbtn), modelbaseclass=VALUES(modelbaseclass);
REPLACE INTO `ds_column` (`table_name`, `column_name`, `default_value`, `default_max_value`, `default_min_value`, `update_value`, `is_primary`, `syncable`, `referenced_table`, `referenced_column_name`, `is_nullable`, `is_referenced`, `writeable`, `note`, `data_type`, `column_key`, `column_type`, `character_maximum_length`, `numeric_precision`, `numeric_scale`, `character_set_name`, `privileges`, `existsreal`, `deferedload`, `hint`, `fieldtype`) VALUES ('tualocms_page_middleware','position','999',0,0,'',0,0,'','','YES','',1,'','int','','int(11)',NULL,10,0,NULL,'select,insert,update,references',1,0,'',''),
('tualocms_page_middleware','tualocms_middleware',NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','PRI','varchar(50)',50,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('tualocms_page_middleware','tualocms_page',NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,'NO',NULL,1,NULL,'varchar','PRI','varchar(36)',36,NULL,NULL,'utf8mb4','select,insert,update,references',1,NULL,NULL,''),
('tualocms_page_middleware','valid_from','2023-01-01 00:00:00',0,0,'',0,0,'','','NO','',1,'','datetime','','datetime',NULL,NULL,NULL,NULL,'select,insert,update,references',1,0,'',''),
('tualocms_page_middleware','valid_until','2099-12-31 23:59:59',0,0,'',0,0,'','','NO','',1,'','datetime','','datetime',NULL,NULL,NULL,NULL,'select,insert,update,references',1,0,'','');
INSERT  IGNORE INTO `ds_column_list_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `editor`, `position`, `summaryrenderer`, `renderer`, `summarytype`, `hidden`, `active`, `filterstore`, `grouped`, `flex`, `direction`, `align`, `listfiltertype`, `hint`) VALUES ('tualocms_page_middleware','position','DE','Position','gridcolumn','',0,'number','','count',0,1,'',0,1.00,'','left','','NULL'),
('tualocms_page_middleware','tualocms_middleware','DE','Middleware','column_tualocms_middleware_tualocms_middleware',NULL,2,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('tualocms_page_middleware','tualocms_page','DE','Seite','column_tualocms_page_tualocms_page',NULL,1,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('tualocms_page_middleware','valid_from','DE','Von','gridcolumn',NULL,3,'','','',0,1,'',0,1.00,'ASC','left','',NULL),
('tualocms_page_middleware','valid_until','DE','Bis','gridcolumn',NULL,4,'','','',0,1,'',0,1.00,'ASC','left','',NULL);
INSERT  IGNORE INTO `ds_column_form_label` (`table_name`, `column_name`, `language`, `label`, `xtype`, `field_path`, `position`, `hidden`, `active`, `allowempty`, `fieldgroup`, `flex`, `hint`) VALUES ('tualocms_page_middleware','position','DE','Position','displayfield','Allgemein/Angaben',0,0,1,0,'1',1.00,'\'\''),
('tualocms_page_middleware','tualocms_middleware','DE','Middleware','combobox_tualocms_middleware_tualocms_middleware','Allgemein/Angaben',2,0,1,0,'1',1.00,'\'\''),
('tualocms_page_middleware','tualocms_page','DE','Seite','combobox_tualocms_page_tualocms_page','Allgemein/Angaben',1,0,1,0,'1',1.00,'\'\''),
('tualocms_page_middleware','valid_from','DE','Von','datetimefield','Allgemein/Angaben',3,0,1,0,'Aktiv',1.00,'\'\''),
('tualocms_page_middleware','valid_until','DE','Bis','datetimefield','Allgemein/Angaben',4,0,1,0,'Aktiv',1.00,'\'\'');
INSERT  IGNORE INTO `ds_reference_tables` (`table_name`, `reference_table_name`, `columnsdef`, `constraint_name`, `active`, `searchable`, `autosync`, `position`, `path`, `existsreal`, `tabtitle`) VALUES ('tualocms_page_middleware','tualocms_middleware','{\"tualocms_middleware\":\"tualocms_middleware\"}','fk_tualocms_page_middleware_middleware',1,0,0,999,'',1,''),
('tualocms_page_middleware','tualocms_page','{\"tualocms_page\":\"tualocms_page\"}','fk_tualocms_page_middleware_page',1,0,0,999,'',1,'');
INSERT  IGNORE INTO `ds_access` (`role`, `table_name`, `read`, `write`, `delete`, `append`, `existsreal`) VALUES ('administration','tualocms_page_middleware',1,1,1,1,0);
